# ============================================================================
# GAME REPOSITORY
# ============================================================================
# This file was auto-generated on: 2025-09-10 09:58:05 WAT
# It contains asynchronous functions for managing access to the database
# in a MongoDB database using FastAPI.
#
# DO NOT EDIT THIS FILE MANUALLY - RE-RUN THE GENERATOR INSTEAD. OR IF YOU WANT TO EDIT JUST ADD LEAVE OTHER FUNCTIONS THE WAY YOU MET THEM
# ============================================================================

from pymongo import ReturnDocument
from core.database import db
from fastapi import HTTPException,status
from typing import List,Optional
from bson import ObjectId
from schemas.game import GameUpdate, GameCreate, GameOut

async def create_game(game_data: GameCreate) -> GameOut:
    game_dict = game_data.model_dump(mode='json')

    result =await db.games.insert_one(game_dict)
    result = await db.games.find_one(filter={"_id":result.inserted_id})
    returnable_result = GameOut(**result)
    return returnable_result

async def get_game(filter_dict: dict) -> Optional[GameOut]:
    try:
        result = await db.games.find_one(filter_dict)

        if result is None:
            return None

        return GameOut(**result)

    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An error occurred while fetching game: {str(e)}"
        )
    
async def get_games(filter_dict: dict = {},start=0,stop=100) -> List[GameOut]:
    try:
        if filter_dict is None:
            filter_dict = {}

        cursor = (db.games.find(filter_dict)
        .skip(start)
        .limit(stop - start)
        )
        game_list = []

        async for doc in cursor:
            game_list.append(GameOut(**doc))

        return game_list

    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An error occurred while fetching games: {str(e)}"
        )
async def update_game(filter_dict: dict, game_data: GameUpdate) -> GameOut:
    result = await db.games.find_one_and_update(
        filter_dict,
        {"$set": game_data.model_dump(exclude_none=True)},
        return_document=ReturnDocument.AFTER
    )
    returnable_result = result
    return returnable_result

async def delete_game(filter_dict: dict):
    return await db.games.delete_one(filter_dict)


async def get_expirable_games(before_timestamp: int) -> List[GameOut]:
    cursor = db.games.find(
        {
            "status": {"$in": ["waiting", "started"]},
            "date_created": {"$lt": before_timestamp},
        }
    )
    items: list[GameOut] = []
    async for doc in cursor:
        items.append(GameOut(**doc))
    return items


async def mark_games_expired(game_ids: list[str]) -> int:
    if not game_ids:
        return 0
    object_ids = [ObjectId(game_id) for game_id in game_ids if ObjectId.is_valid(game_id)]
    result = await db.games.update_many(
        {"_id": {"$in": object_ids}},
        {"$set": {"status": "expired"}},
    )
    return int(result.modified_count)
