# ============================================================================
# LEADERBOARD REPOSITORY
# ============================================================================
# This file was auto-generated on: 2025-09-10 09:58:16 WAT
# It contains asynchronous functions for managing access to the database
# in a MongoDB database using FastAPI.
#
# DO NOT EDIT THIS FILE MANUALLY - RE-RUN THE GENERATOR INSTEAD. OR IF YOU WANT TO EDIT JUST ADD LEAVE OTHER FUNCTIONS THE WAY YOU MET THEM
# ============================================================================

from pymongo import ReturnDocument
from core.database import db
from fastapi import HTTPException,status
from typing import List,Optional
from schemas.leaderboard import LeaderboardUpdate, LeaderboardCreate, LeaderboardOut

async def create_leaderboard(leaderboard_data: LeaderboardCreate) -> LeaderboardOut:
    leaderboard_dict = leaderboard_data.model_dump()
    result =await db.leaderboards.insert_one(leaderboard_dict)
    result = await db.leaderboards.find_one(filter={"_id":result.inserted_id})
    returnable_result = LeaderboardOut(**result)
    return returnable_result

async def get_leaderboard(filter_dict: dict) -> Optional[LeaderboardOut]:
    try:
        result = await db.leaderboards.find_one(filter_dict)

        if result is None:
            return None

        return LeaderboardOut(**result)

    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An error occurred while fetching leaderboard: {str(e)}"
        )
    
async def get_leaderboards(filter_dict: dict = {},start=0,stop=100) -> List[LeaderboardOut]:
    try:
        if filter_dict is None:
            filter_dict = {}

        cursor = (db.leaderboards.find(filter_dict)
        .skip(start)
        .limit(stop - start)
        )
        leaderboard_list = []

        async for doc in cursor:
            leaderboard_list.append(LeaderboardOut(**doc))

        return leaderboard_list

    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An error occurred while fetching leaderboards: {str(e)}"
        )
async def update_leaderboard(filter_dict: dict, leaderboard_data: LeaderboardUpdate) -> LeaderboardOut:
    result = await db.leaderboards.find_one_and_update(
        filter_dict,
        {"$set": leaderboard_data.model_dump()},
        return_document=ReturnDocument.AFTER
    )
    returnable_result = LeaderboardOut(**result)
    return returnable_result

async def delete_leaderboard(filter_dict: dict):
    return await db.leaderboards.delete_one(filter_dict)