# ============================================================================
# MATCH REPOSITORY
# ============================================================================
# This file was auto-generated on: 2025-09-10 09:57:27 WAT
# It contains asynchronous functions for managing access to the database
# in a MongoDB database using FastAPI.
#
# DO NOT EDIT THIS FILE MANUALLY - RE-RUN THE GENERATOR INSTEAD. OR IF YOU WANT TO EDIT JUST ADD LEAVE OTHER FUNCTIONS THE WAY YOU MET THEM
# ============================================================================

from pymongo import ReturnDocument
from core.database import db
from fastapi import HTTPException,status
from typing import List,Optional
from schemas.match import MatchUpdate, MatchCreate, MatchOut

async def create_match(match_data: MatchCreate) -> MatchOut:
    match_dict = match_data.model_dump()
    result =await db.matchs.insert_one(match_dict)
    result = await db.matchs.find_one(filter={"_id":result.inserted_id})
    returnable_result = MatchOut(**result)
    return returnable_result

async def get_match(filter_dict: dict) -> Optional[MatchOut]:
    try:
        result = await db.matchs.find_one(filter_dict)

        if result is None:
            return None

        return MatchOut(**result)

    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An error occurred while fetching match: {str(e)}"
        )
    
async def get_matchs(filter_dict: dict = {},start=0,stop=100) -> List[MatchOut]:
    try:
        if filter_dict is None:
            filter_dict = {}

        cursor = (db.matchs.find(filter_dict)
        .skip(start)
        .limit(stop - start)
        )
        match_list = []

        async for doc in cursor:
            match_list.append(MatchOut(**doc))

        return match_list

    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An error occurred while fetching matchs: {str(e)}"
        )
async def update_match(filter_dict: dict, match_data: MatchUpdate) -> MatchOut:
    result = await db.matchs.find_one_and_update(
        filter_dict,
        {"$set": match_data.model_dump()},
        return_document=ReturnDocument.AFTER
    )
    returnable_result = MatchOut(**result)
    return returnable_result

async def delete_match(filter_dict: dict):
    return await db.matchs.delete_one(filter_dict)