# ============================================================================
# PLAYER REPOSITORY
# ============================================================================
# This file was auto-generated on: 2025-09-10 09:57:36 WAT
# It contains asynchronous functions for managing access to the database
# in a MongoDB database using FastAPI.
#
# DO NOT EDIT THIS FILE MANUALLY - RE-RUN THE GENERATOR INSTEAD. OR IF YOU WANT TO EDIT JUST ADD LEAVE OTHER FUNCTIONS THE WAY YOU MET THEM
# ============================================================================

from pymongo import ReturnDocument
from core.database import db
from fastapi import HTTPException,status
from typing import List,Optional
from schemas.player import PlayerUpdate, PlayerCreate, PlayerOut

async def create_player(player_data: PlayerCreate) -> PlayerOut:
    player_dict = player_data.model_dump()
    result =await db.players.insert_one(player_dict)
    result = await db.players.find_one(filter={"_id":result.inserted_id})
    returnable_result = PlayerOut(**result)
    return returnable_result

async def get_player(filter_dict: dict) -> Optional[PlayerOut]:
    try:
        result = await db.players.find_one(filter_dict)

        if result is None:
            return None

        return PlayerOut(**result)

    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An error occurred while fetching player: {str(e)}"
        )
    
async def get_players(filter_dict: dict = {},start=0,stop=100) -> List[PlayerOut]:
    try:
        if filter_dict is None:
            filter_dict = {}

        cursor = (db.players.find(filter_dict)
        .skip(start)
        .limit(stop - start)
        )
        player_list = []

        async for doc in cursor:
            player_list.append(PlayerOut(**doc))

        return player_list

    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An error occurred while fetching players: {str(e)}"
        )
async def update_player(filter_dict: dict, player_data: PlayerUpdate) -> PlayerOut:
    result = await db.players.find_one_and_update(
        filter_dict,
        {"$set": player_data.model_dump()},
        return_document=ReturnDocument.AFTER
    )
    returnable_result = PlayerOut(**result)
    return returnable_result

async def delete_player(filter_dict: dict):
    return await db.players.delete_one(filter_dict)


async def get_player_by_user_and_game(user_id: str, game_id: str) -> Optional[PlayerOut]:
    doc = await db.players.find_one({"user_id": user_id, "game_id": game_id})
    if doc is None:
        return None
    return PlayerOut(**doc)
