# ============================================================================
# SCORES REPOSITORY
# ============================================================================
# This file was auto-generated on: 2025-09-10 09:58:09 WAT
# It contains asynchronous functions for managing access to the database
# in a MongoDB database using FastAPI.
#
# DO NOT EDIT THIS FILE MANUALLY - RE-RUN THE GENERATOR INSTEAD. OR IF YOU WANT TO EDIT JUST ADD LEAVE OTHER FUNCTIONS THE WAY YOU MET THEM
# ============================================================================

from pymongo import ReturnDocument
from core.database import db
from fastapi import HTTPException,status
from typing import List,Optional
from schemas.scores import ScoresUpdate, ScoresCreate, ScoresOut

async def create_scores(scores_data: ScoresCreate) -> ScoresOut:
    scores_dict = scores_data.model_dump()
    result =await db.scoress.insert_one(scores_dict)
    result = await db.scoress.find_one(filter={"_id":result.inserted_id})
    returnable_result = ScoresOut(**result)
    return returnable_result

async def get_scores(filter_dict: dict) -> Optional[ScoresOut]:
    try:
        result = await db.scoress.find_one(filter_dict)

        if result is None:
            return None

        return ScoresOut(**result)

    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An error occurred while fetching scores: {str(e)}"
        )
    
async def get_scoress(filter_dict: dict = {},start=0,stop=100) -> List[ScoresOut]:
    try:
        if filter_dict is None:
            filter_dict = {}

        cursor = (db.scoress.find(filter_dict)
        .skip(start)
        .limit(stop - start)
        )
        scores_list = []

        async for doc in cursor:
            scores_list.append(ScoresOut(**doc))

        return scores_list

    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An error occurred while fetching scoress: {str(e)}"
        )
async def update_scores(filter_dict: dict, scores_data: ScoresUpdate) -> ScoresOut:
    result = await db.scoress.find_one_and_update(
        filter_dict,
        {"$set": scores_data.model_dump()},
        return_document=ReturnDocument.AFTER
    )
    returnable_result = ScoresOut(**result)
    return returnable_result

async def delete_scores(filter_dict: dict):
    return await db.scoress.delete_one(filter_dict)


async def get_scores_for_players(player_ids: list[str]) -> List[ScoresOut]:
    if not player_ids:
        return []
    cursor = db.scoress.find({"player_id": {"$in": player_ids}})
    items: list[ScoresOut] = []
    async for doc in cursor:
        items.append(ScoresOut(**doc))
    return items
