# ============================================================================
# SECRET REPOSITORY
# ============================================================================
# This file was auto-generated on: 2025-09-10 10:02:33 WAT
# It contains asynchronous functions for managing access to the database
# in a MongoDB database using FastAPI.
#
# DO NOT EDIT THIS FILE MANUALLY - RE-RUN THE GENERATOR INSTEAD. OR IF YOU WANT TO EDIT JUST ADD LEAVE OTHER FUNCTIONS THE WAY YOU MET THEM
# ============================================================================

from pymongo import ReturnDocument
from core.database import db
from fastapi import HTTPException,status
from typing import List,Optional
from schemas.secret import SecretUpdate, SecretCreate, SecretOut

async def create_secret(secret_data: SecretCreate) -> SecretOut:
    secret_dict = secret_data.model_dump()
    result =await db.secrets.insert_one(secret_dict)
    result = await db.secrets.find_one(filter={"_id":result.inserted_id})
    returnable_result = SecretOut(**result)
    return returnable_result

async def get_secret(filter_dict: dict) -> Optional[SecretOut]:
    try:
        result = await db.secrets.find_one(filter_dict)

        if result is None:
            return None

        return SecretOut(**result)

    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An error occurred while fetching secret: {str(e)}"
        )
    
async def get_secrets(filter_dict: dict = {},start=0,stop=100) -> List[SecretOut]:
    try:
        if filter_dict is None:
            filter_dict = {}

        cursor = (db.secrets.find(filter_dict)
        .skip(start)
        .limit(stop - start)
        )
        secret_list = []

        async for doc in cursor:
            secret_list.append(SecretOut(**doc))

        return secret_list

    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An error occurred while fetching secrets: {str(e)}"
        )
async def update_secret(filter_dict: dict, secret_data: SecretUpdate) -> SecretOut:
    result = await db.secrets.find_one_and_update(
        filter_dict,
        {"$set": secret_data.model_dump()},
        return_document=ReturnDocument.AFTER
    )
    returnable_result = SecretOut(**result)
    return returnable_result

async def delete_secret(filter_dict: dict):
    return await db.secrets.delete_one(filter_dict)