# ============================================================================
# USER REPOSITORY
# ============================================================================
# This file was auto-generated on: 2025-09-10 09:57:58 WAT
# It contains asynchronous functions for managing access to the database
# in a MongoDB database using FastAPI.
#
# DO NOT EDIT THIS FILE MANUALLY - RE-RUN THE GENERATOR INSTEAD. OR IF YOU WANT TO EDIT JUST ADD LEAVE OTHER FUNCTIONS THE WAY YOU MET THEM
# ============================================================================

from pymongo import ReturnDocument
from core.database import db
from typing import List, Optional
from schemas.user import UserUpdate, UserCreate, UserOut, UserRecord

async def create_user(user_data: UserCreate) -> UserOut:
    user_dict = user_data.model_dump(mode="json")
    result =await db.users.insert_one(user_dict)
    result = await db.users.find_one(filter={"_id":result.inserted_id})
  
    returnable_result = UserOut(**result)
    return returnable_result

async def get_user(filter_dict: dict) -> Optional[UserRecord]:
    result = await db.users.find_one(filter_dict)
    if result is None:
        return None
    return UserRecord(**result)
    
async def get_users(filter_dict: dict | None = None, start: int = 0, stop: int = 100) -> List[UserOut]:
    if filter_dict is None:
        filter_dict = {}

    cursor = (db.users.find(filter_dict)
    .skip(start)
    .limit(max(stop - start, 0))
    )
    user_list = []

    async for doc in cursor:
        user_list.append(UserOut(**doc))

    return user_list
async def update_user(filter_dict: dict, user_data: UserUpdate) -> UserOut:
    result = await db.users.find_one_and_update(
        filter_dict,
        {"$set": user_data.model_dump(exclude_none=True)},
        return_document=ReturnDocument.AFTER
    )
    returnable_result = UserOut(**result)
    return returnable_result

async def delete_user(filter_dict: dict):
    return await db.users.delete_one(filter_dict)
